config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'
  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind, optional: true
  has_one :address, :dependent => :destroy
  has_many :phones, :dependent => :destroy

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true
  validates :name, presence: true, length: { minimum: 3}
  validates :email, presence: true
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :contacts, :dependent => :destroy
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_options_for_select, only: [:new, :edit, :update, :create]
  http_basic_authenticate_with name: "luiz", password: "123", only: :destroy

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(:name).page(params[:page]).per(15)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_path, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def set_options_for_select
    @kind_options_for_select = Kind.all
  end


  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:name, :email, :kind_id, :rmk,
                                    address_attributes: [:street, :city, :state],
                                    phones_attributes: [:id, :phone, :_destroy])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: %i[ show edit update destroy ]

  # GET /kinds or /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1 or /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds or /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to kind_url(@kind), notice: "Kind was successfully created." }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1 or /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to kind_url(@kind), notice: "Kind was successfully updated." }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1 or /kinds/1.json
  def destroy
    @kind.destroy

    respond_to do |format|
      format.html { redirect_to kinds_url, notice: "Kind was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  ESTADOS_BRASILEIROS = [
    ["Acre", "AC"],
    ["Alagoas", "AL"],
    ["Amapá", "AP"],
    ["Amazonas", "AM"],
    ["Bahia", "BA"],
    ["Ceará", "CE"],
    ["Distrito Federal", "DF"],
    ["Espírito Santo", "ES"],
    ["Goiás", "GO"],
    ["Maranhão", "MA"],
    ["Mato Grosso", "MT"],
    ["Mato Grosso do Sul", "MS"],
    ["Minas Gerais", "MG"],
    ["Pará", "PA"],
    ["Paraíba", "PB"],
    ["Paraná", "PR"],
    ["Pernambuco", "PE"],
    ["Piauí", "PI"],
    ["Rio de Janeiro", "RJ"],
    ["Rio Grande do Norte", "RN"],
    ["Rio Grande do Sul", "RS"],
    ["Rondônia", "RO"],
    ["Roraima", "RR"],
    ["Santa Catarina", "SC"],
    ["São Paulo", "SP"],
    ["Sergipe", "SE"],
    ["Tocantins", "TO"]
  ]
  def options_for_states(selected)
    options_for_select(ESTADOS_BRASILEIROS, selected)
  end


end

app/helpers/contacts_helper.rb
module ContactsHelper

  def remove_faker_characters_rmk(rmk)
    rmk.gsub('[', "").gsub(']', "")
  end

end

app/helpers/home_helper.rb
module HomeHelper
  def mostrar_meu_nome
    "Escolha uma opção abaixo:"
  end
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact, html: { class: "basic-grey" }) do |f| %>

  <h1>Contatos</h1>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :kind_id %><br>
    <%= f.select :kind_id,
                 options_for_select(
                   Kind.all.collect { |kind|
                     [kind.description, kind.id] },
                   :selected => f.object.kind_id),
                 { :include_blank => "Outros..." },
                 :class => "form-control chosen-select"
    %>
  </div>

  <%= f.fields_for :address do |address_fields| %>
    <div class="field">
      <%= address_fields.label :street %><br>
      <%= address_fields.text_field :street %>
    </div>
    <div class="field">
      <%= address_fields.label :city %><br>
      <%= address_fields.text_field :city %>
    </div>
    <div class="field">
      <%= address_fields.label :state %><br>
      <%= address_fields.select :state, options_for_states(@contact.address.state) %>
    </div>
  <% end %>

  <div id="phones">
    <%= f.fields_for :phones do |phones_fields| %>
      <%= render partial: "phone_fields", locals: { f: phones_fields } %>
    <% end %>


    <div class="field">
      <%= f.label :phones, "->" %><br>
      <%= link_to_add_association('[Adicionar Telefone]', f, :phones) %>
    </div>
  </div>

  <div class="field">
    <%= f.label :rmk %>
    <%= f.text_area :rmk %>
  </div>


  <div class="field">
    <%= f.label " " %>
    <%= f.submit "Enviar", class: "btn btn-success" %>
    <%= link_to 'Voltar', contacts_path, class: "btn btn-primary" %>
  </div>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{pluralize(@contact.errors.count, 'error')} #{t('messages.errors')}:" %></h2>

      <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "phone-field" %>
    <%= link_to_remove_association('remover', f)%>
  </div>
</div>

app/views/contacts/edit.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/index.html.erb
<br/>
<div class="basic-grey">

  <script>
      $.notify("<%= notice %>", "success");
  </script>

  <h1><%= "#{t('messages.listing')}" %></h1>

  <table class="table table-dark table-striped">
    <thead>
    <tr>
      <th><%= @contacts.model.human_attribute_name("NOMES") %></th>
      <th><%= @contacts.model.human_attribute_name("TIPOS") %></th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @contacts.each do |contact| %>
      <tr style="background: <%= cycle('white', '#f0f0f5') %>">
        <td><%= contact.name %></td>
        <td>
          <% if contact.kind.present? %>
            <%= contact.kind.description %>
          <% end %>
        </td>
        <td><%= link_to t('buttons.edit'), edit_contact_path(contact) %></td>
        <td><%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('messages.confirm') } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>
  <%= paginate @contacts %>
  <br>
  <%= link_to 'Voltar', root_path, class: "btn btn-primary" %>
  <%= link_to t('buttons.new'), new_contact_path, class: "btn btn-success"%>
</div>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Kind:</strong>
  <% if @contact.kind.present? %>
    <%= @contact.kind.description %>
  <% end %>
</p>

<p>
  <strong>Rmk:</strong>
  <%= @contact.rmk %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
<div class="basic-grey">
  <h1>Seja bem-vindo!</h1>

<ul>
  <li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
    <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293z"/>
    <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293z"/>
  </svg> - <%= link_to t("Contatos"), contacts_path %></li>
  <li><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list-ul" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M5 11.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m-3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2m0 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2m0 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2"/>
  </svg> - <%= link_to "Tipos", kinds_path%></li>
</ul>
</div>

app/views/kinds/_form.html.erb
<%= form_with(model: kind, local: true) do |form| %>
  <% if kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
      <% kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<h1>Editing Kind</h1>

<%= render 'form', kind: @kind %>

<%= link_to 'Show', @kind %> |
<%= link_to 'Back', kinds_path %>

app/views/kinds/index.html.erb
<div class="basic-grey">
<p id="notice"><%= notice %></p>

<h1>Tipos</h1>

<table>
  <thead>
    <tr>
      <th>Descrição</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td style="text-align: center"><%= kind.description %></td>
        <td style="text-align: center"><%= link_to 'Editar', edit_kind_path(kind) %></td>
        <td style="text-align: center"><%= link_to 'Apagar', kind, method: :delete, data: { confirm: 'Você tem certeza' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Novo Tipo', new_kind_path, class: "btn btn-success" %>
  <%= link_to 'Voltar', root_path, class: "btn btn-primary" %>
</div>

app/views/kinds/new.html.erb
<h1>New Kind</h1>

<%= render 'form', kind: @kind %>

<%= link_to 'Back', kinds_path %>

app/views/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @kind.description %>
</p>

<%= link_to 'Edit', edit_kind_path(@kind) %> |
<%= link_to 'Back', kinds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notebook</title>
    <script src="https://unpkg.com/feather-icons"></script>
    <%= stylesheet_link_tag params[:controller]%>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag params[:controller] %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script>
        feather.replace();
    </script>
  </body>

</html>